name: generate-markdown

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: fabasoad/yaml-json-xml-converter-action@v1.0.0
      id: yaml2json
      with:
        path: 'schema/dataset.schema.yaml'
        from: 'yaml'
        to: 'json'
    - name: Output yaml2json result
      run: echo "${{ steps.yaml2json.outputs.data }} > schema/dataset.schema.json"
    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    
    - name: Install jsonschema2md package
      run: npm install -g @adobe/jsonschema2md
    
    - name: Run jsonschema2md package to generate markdown
      run: jsonschema2md -n -d schema -o docs -x -
    
    - name: Auto-Commit generate-markdown
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Commit generated markdown
        branch: ${{ github.head_ref }}
        commit_user_name: Susheel Varma
        commit_user_email: susheel.varma@hdruk.ac.uk
        commit_author: Susheel Varma <susheel.varma@hdruk.ac.uk>
